### PR TITLE
Fix 'ReferenceError: sizeEdgeVal' bug when adding a relation

### LINKED ISSUE #108: ReferenceError: sizeEdgeVal is not defined error on osd branch
The latest version on the OSD branch doesn't allow to create node-relation networks. It raises the `ReferenceError` when drawing the relationships.

```
ReferenceError: sizeEdgeVal is not defined
    dataNodes http://localhost:5601/3032/bundles/plugin/kbnNetwork/kbnNetwork.plugin.js:135
    _ret http://localhost:5601/3032/bundles/plugin/kbnNetwork/kbnNetwork.plugin.js:135
    renderVis http://localhost:5601/3032/bundles/plugin/kbnNetwork/kbnNetwork.plugin.js:135
    c http://localhost:5601/3032/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:430
    completeTask http://localhost:5601/3032/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:430
    r http://localhost:5601/3032/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:430
osd-ui-shared-deps.js:430:78980
ReferenceError: sizeEdgeVal is not defined
    dataNodes http://localhost:5601/3032/bundles/plugin/kbnNetwork/kbnNetwork.plugin.js:135
    _ret http://localhost:5601/3032/bundles/plugin/kbnNetwork/kbnNetwork.plugin.js:135
    renderVis http://localhost:5601/3032/bundles/plugin/kbnNetwork/kbnNetwork.plugin.js:135
    c http://localhost:5601/3032/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:430
    completeTask http://localhost:5601/3032/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:430
    r http://localhost:5601/3032/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:430
 Possibly unhandled rejection: {} osd-ui-shared-deps.js:430:78980
```

### PR DESCRIPTION
**Pull request by evamillan**
Fixes #108.

### CODE REVIEW

**Comment by sduenas** [comment]
@dlumbrer for the record, I've been testing it and it solves the bug.

**Comment by dlumbrer** [comment]
Perfect!, thanks to both!

**Comment by sduenas** [comment]
@dlumbrer thanks for the fast respose. Would you mind to generate a new release of this plugin?

**Comment by dlumbrer** [comment]
> @dlumbrer thanks for the fast respose. Would you mind to generate a new release of this plugin?

Sure!, it is generating (under the `osd-1.3.2-2` tag/release)

Edit: released! cc @sduenas

**Comment by sduenas** [comment]
I see it. Thanks @dlumbrer !

**Pull request merged**
